---
title: "communication du 11 août 2022"
output: distill::distill_article
---
Chères et Chers Participant·es à la session 1 de la formation FOCUS, 

A l'orée d'une reprise scolaire que nous vous souhaitons fructueuse, voici quelques informations visant à accompagner votre entrée en formation continue FOCUS.

Pour la bonne forme, nous confirmons par ce mail que votre inscription est bien prise en compte.

Le jour de la première conférence approche à grands pas. Nous vous attendons

le mercredi 31 août 2022 à l’aula de la Tuilerie (St-Maurice) à 14h30 (jusqu'à 17h00).

Un plan de situation est à votre disposition sur notre page web : hepvs.ch > Formation continue > cours obligatoires > Formation FOCUS > Ressources

Lien direct vers le plan de situation : https://hepvs.ch/images/FCE/Cours_Oblig/focus_plandesituation.pdf (à copier/coller dans votre navigateur)

Cette première conférence en présentiel, sous l’égide de notre partenaire l’institut de pédagogie curative (IPC) de l’Université de Fribourg, donnera la part belle aux questions liées à l'autisme. 

Au cours de cette conférence et à la suite d'un mot officiel de l'Office de l'Enseignement Spécialisé, le comité de pilotage de FOCUS vous transmettra les informations utiles pour vous permettre d'accéder à votre espace de formation FOCUS hébergé via Microsoft Teams. C'est dans cet espace privé que seront regroupées et mises à jour les informations et autres ressources liées à votre parcours de formation. En attendant, vous pouvez toujours retrouver les horaires de la session 1 dans le descriptif du cours 14.13 où vous vous êtes inscrit·es.

Le lien direct est (copier/coller dans votre navigateur) : https://old2021.hepvs.ch/fmdb/fr2/index.php?events[a]=details&events[v][id]=WVE_P6KNFJUKQ6M9PYJFI220524.114946 

Nous restons à votre disposition au besoin via l'adresse mail focus@hepvs.ch.

Au plaisir de vous accueillir le 31 août !

Avec nos meilleures salutations, 

Pour le comité de pilotage, 
Anita Jovanovska et Nicolas Bressoud
