---
title: "Formation continue des ES du VS Romand"
description: |
  Historique des présentations aux partenaires.
author:
  - name: Nicolas Bressoud 
    url: https://hepvs.ch
    affiliation: Haute école pédagogique du Valais
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Rencontre avec l'OES - 15 septembre 2021

Lien : <https://bresnico.github.io/formation_es_rencontre_sept2021/> 

- Validation de la structure de la formation
- Validation des jalons (deadlines) principaux
- Demande de refonte de la partie "pratique" de la formation

## Rencontre avec l'OES - 8 novembre 2021

Lien : <https://bresnico.github.io/seance-oes-8-novembre-2021/>

- Validation de la partie pratique de la formation

## Rencontre avec la direction HEP-VS - 25 novembre 2021

- Validation interne de la stratégie budgétaire
- Ajournement de la formalisation de partenariat interinstitutionnel

Lien : <https://bresnico.github.io/psu1_25_novembre_2021/>

## Conseil scientifique (séance 1) - 1er décembre 2021

Lien : <https://bresnico.github.io/cs1_1_decembre_2021/>

- Première identification des contenus

## Groupe consultatif (séance 1) - 6 décembre 2021

Lien : <https://bresnico.github.io/gc1_6_decembre_2021/>

- Listing de risques et opportunités en lien avec tout le projet
- Commentaires sur l'adéquation entre les contenus et le terrain

## Rencontre HEP-VS - OES - SE - 21 décembre 2021

Lien : <https://bresnico.github.io/se_21_decembre_2021/>

- Mise au point de la stratégie budgétaire commune

## Conseil scientifique (séance 2) - 10 janvier 2022

Lien : <https://bresnico.github.io/cs2_10_janvier_2022/>

- Approfondissement des 4 thèmes
- Définition du modèle sous-jacent

## Groupe consultatif (séance 2) - 11 janvier 2022

Lien : <https://bresnico.github.io/gc2_11_janvier_2022/>

- Prise de position sur les technologies utilisées
- Prise de position sur l'alternance présentiel-distanciel

## Rencontre avec l'OES - 24 janvier 2022

Lien : <https://bresnico.github.io/oes3-24-janvier-2022/>

- Identification des risques liés aux jalons budgétaires
- Adaptation du calendrier d'avancement du projet (avec scénario de report d'1 an)
- Information sur les responsabilités entre les organes


## Rencontre avec le comité scientifique (CS3) - 22 mars 2022

Lien : <https://bresnico.github.io/cs3-22-mars-2022/>

- Fixation des contenus
- Répartition des missions et préparation des équipes

## Rencontre avec l'OES - 22 mars 2022

Lien : <https://bresnico.github.io/oes4-22-mars-2022/>

- [prévu] Go/No-Go pour communication fin mars et démarrage formation en août 2022
- [prévu] Nom de la formation
- [prévu] Collaboration avec les insitutions partenaires
- [prévu] Adaptation du calendrier d'avancement du projet


## Rencontre avec le groupe consultatif (GC3) - 4 mai 2022

Lien : <https://bresnico.github.io/gc3-4-mai-2022/>

- [prévu] Accueil
- [prévu] Organes de la formation (organigramme final, rôle du client)
- [prévu] Communication autour de la formation (nom de la formation, responsabilités, jalons)
- [prévu] Structure finale de la formation (contenus, équipes de formation)
- [prévu] Modalités finales de la formation (part technologique, ressources à disposition)
- [prévu] Horaires en consultation
- [prévu] Prochaines étapes
- [prévu] Divers

## Rencontre avec le comité scientifique (CS4) - 9 mai 2022

Lien : <https://bresnico.github.io/cs4-9-mai-2022/>

- [prévu] Accueil
- [prévu] Thème 4 : forme, contenu, responsabilités
- [prévu] Horaires en consultation
- [prévu] Communication autour de la formation
- [prévu] Structure finale de la formation (contenus, équipes de formation)
- [prévu] Modalités finales de la formation (part technologique, ressources à disposition)
- [prévu] Prochaines étapes
- [prévu] Divers

## Rencontre avec l'OES (OES5) - 7 juin 2022

Lien : <https://bresnico.github.io/oes5-7-juin-2022/>

- à venir...

## Rencontre avec le comité scientifique (CS5) - 13 juin 2022

Lien : <https://bresnico.github.io/cs5-13-juin-2022/>

- [prévu] Accueil
- [prévu] Thème 4 : contenu, delivrable et modalités
- [prévu] Informations sur les affaires courantes
- [prévu] Divers

Fait avec Distill pour R Markdown : <https://rstudio.github.io/distill>.





