---
title: "Formation continue des ES du VS Romand"
description: |
  Historique des présentations aux partenaires.
author:
  - name: Nicolas Bressoud 
date: "`r Sys.Date()`"
toc: false
lang: fr
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Historique des communications aux participant·es

- [Communication du 11 août 2022 via la formation continue](comm-11-aout-2022.html)

## Publication des horaires

- [Lien vers le calendrier (master)](https://bresnico.notion.site/1eb327c812274cee988ee35c1c5d6c1b?v=bf696369214a42319b72b15ff114c8a3) 
- [Liste des événements de la session 1](https://bresnico.notion.site/1eb327c812274cee988ee35c1c5d6c1b?v=f19a70ad82c540cb8b464e4bd34e64b7)
- [Liste des événements de la session 2](https://bresnico.notion.site/1eb327c812274cee988ee35c1c5d6c1b?v=41551bd371bd4365a20937bca9ab20d1)
- [Liste des événements de la session 3](https://bresnico.notion.site/1eb327c812274cee988ee35c1c5d6c1b?v=f4395c8c3b934e5ca9fc9735d37c1a09)


## Rencontre avec l'OES - 15 septembre 2021

Lien : <https://bresnico.github.io/formation_es_rencontre_sept2021/> 

- Validation de la structure de la formation
- Validation des jalons (deadlines) principaux
- Demande de refonte de la partie "pratique" de la formation

## Rencontre avec l'OES - 8 novembre 2021

Lien : <https://bresnico.github.io/seance-oes-8-novembre-2021/>

- Validation de la partie pratique de la formation

## Rencontre avec la direction HEP-VS - 25 novembre 2021

- Validation interne de la stratégie budgétaire
- Ajournement de la formalisation de partenariat interinstitutionnel

Lien : <https://bresnico.github.io/psu1_25_novembre_2021/>

## Conseil scientifique (séance 1) - 1er décembre 2021

Lien : <https://bresnico.github.io/cs1_1_decembre_2021/>

- Première identification des contenus

## Groupe consultatif (séance 1) - 6 décembre 2021

Lien : <https://bresnico.github.io/gc1_6_decembre_2021/>

- Listing de risques et opportunités en lien avec tout le projet
- Commentaires sur l'adéquation entre les contenus et le terrain

## Rencontre HEP-VS - OES - SE - 21 décembre 2021

Lien : <https://bresnico.github.io/se_21_decembre_2021/>

- Mise au point de la stratégie budgétaire commune

## Conseil scientifique (séance 2) - 10 janvier 2022

Lien : <https://bresnico.github.io/cs2_10_janvier_2022/>

- Approfondissement des 4 thèmes
- Définition du modèle sous-jacent

## Groupe consultatif (séance 2) - 11 janvier 2022

Lien : <https://bresnico.github.io/gc2_11_janvier_2022/>

- Prise de position sur les technologies utilisées
- Prise de position sur l'alternance présentiel-distanciel

## Rencontre avec l'OES - 24 janvier 2022

Lien : <https://bresnico.github.io/oes3-24-janvier-2022/>

- Identification des risques liés aux jalons budgétaires
- Adaptation du calendrier d'avancement du projet (avec scénario de report d'1 an)
- Information sur les responsabilités entre les organes


## Rencontre avec le comité scientifique (CS3) - 22 mars 2022

Lien : <https://bresnico.github.io/cs3-22-mars-2022/>

- Fixation des contenus
- Répartition des missions et préparation des équipes

## Rencontre avec l'OES - 22 mars 2022

Lien : <https://bresnico.github.io/oes4-22-mars-2022/>

- [prévu] Go/No-Go pour communication fin mars et démarrage formation en août 2022
- [prévu] Nom de la formation
- [prévu] Collaboration avec les insitutions partenaires
- [prévu] Adaptation du calendrier d'avancement du projet


## Rencontre avec le groupe consultatif (GC3) - 4 mai 2022

Lien : <https://bresnico.github.io/gc3-4-mai-2022/>

- [prévu] Accueil
- [prévu] Organes de la formation (organigramme final, rôle du client)
- [prévu] Communication autour de la formation (nom de la formation, responsabilités, jalons)
- [prévu] Structure finale de la formation (contenus, équipes de formation)
- [prévu] Modalités finales de la formation (part technologique, ressources à disposition)
- [prévu] Horaires en consultation
- [prévu] Prochaines étapes
- [prévu] Divers

## Rencontre avec le comité scientifique (CS4) - 9 mai 2022

Lien : <https://bresnico.github.io/cs4-9-mai-2022/>

- Accueil
- Thème 4 : forme, contenu, responsabilités
- Horaires en consultation
- Communication autour de la formation
- Structure finale de la formation (contenus, équipes de formation)
- Modalités finales de la formation (part technologique, ressources à disposition)
- Prochaines étapes
- Divers

## Rencontre avec l'OES (OES5) - 7 juin 2022

Lien : <https://bresnico.github.io/oes5-7-juin-2022/>

- Accueil
- Etat d'avancement - chiffres et dates clés
- Inscriptions, aménagements, équivalences
- Positionnement AMES (AG 2022)
- Prochaines étapes
- Divers


## Rencontre avec le comité scientifique (CS5) - 13 juin 2022

Lien : <https://bresnico.github.io/cs5-13-juin-2022/>

- Accueil
- Thème 4 : contenu, delivrable et modalités
- Forme définitive des “vignettes cliniques”
- Informations sur les affaires courantes
- Divers

## Rencontre avec l'OES (OES6) - 3 novembre 2022

Lien : <https://bresnico.github.io/oes6-3-novembre-2022/>

- Chiffres clés
- Etat des affaires courantes
- Premières régulations à envisager (boucle qualité)

## Présentation au SE et à l'OES - 13 décembre 2022

## Rencontre du Comité scientifique (CS6) - 10 janvier 2023

Lien : <https://bresnico.github.io/cs6-10-janvier-2023/>

- Accueil et informations
- Etat d'avancement
    - généralités
    - session 1 : modalités en cours, bilan de satisfaction du comité scientifique
    - session 2 : avancement des préparatifs, régulations éventuelles
    - session 3 : rappel des modalités
- Finances, administration : bilan et régulations éventuelles
- Divers

## Rencontre du groupe consultatif (GC4) - 25 avril 2023

Lien : <https://bresnico.github.io/gc4-25-avril-2023/>

- Accueil
- Bilan session 1 (chiffres-clés, remédiations apportées)
- Bilan intermédiaire session 2 (chiffres-clés)
- Etat d'avancement des préparatifs session 3
- Divers

## Rencontre avec l'OES (OES7) - 27 avril 2023

Lien : <https://bresnico.github.io/oes7-27-avril-2023/>

- Accueil et informations
- Bilan session 1 (chiffres-clés, remédiations apportées)
- Bilan intermédiaire session 2 (chiffres-clés)
- Etat d'avancement des préparatifs session 3
- Après FOCUS ?
- Divers

## Rencontre du groupe consultatif (GC5) - XX janvier 2024

Lien : <>

- Accueil et validation de l'OJ
- Validation du PV de la séance 4
- Retour qualité sur la session 2
- Suite et fin de la formation (session 3, verrée de clôture)
- Après Focus ?
- Divers
